<html><head></head><body>
<div class="book" title="Function panic and recovery" id="164MG1-9c484ed022e64a0fb0e1aebf8e05d4fd">
<div class="book" title="Function panic"><div class="book"><div class="book"><div class="book"><h2 class="title1" id="calibre_pb_1"><a id="ch05lvl2sec92" class="calibre1"/>Function panic</h2></div></div></div><p class="calibre10">During execution, a function may panic because of any one of following:</p><div class="book"><ul class="itemizedlist"><li class="listitem">Explicitly calling the <span class="strong"><strong class="calibre2">panic</strong></span> built-in function</li><li class="listitem">Using a source code package that panics due to an abnormal state</li><li class="listitem">Accessing a nil value or an out-of-bound array element</li><li class="listitem">Concurrency deadlock</li></ul></div><p class="calibre10">When a function panics, it aborts and executes its deferred calls. Then its caller panics, causing a chain reaction as illustrated in the following figure:</p><div class="mediaobject"><img src="../images/00014.jpeg" alt="Function panic" class="calibre14"/></div><p class="calibre15"> </p><p class="calibre10">The panic sequence continues all the way up the call stack until the <code class="email">main</code> function is reached and the program exits (crashes). The following source code snippet shows a version of the anagram program that will cause an explicit panic if an output anagram file already exists when it tries to create one. This is done illustratively to cause the <code class="email">write</code> function to panic when there is a file error:</p><pre class="programlisting">package main 
... 
func write(fname string, anagrams map[string][]string) { 
   file, err := os.OpenFile( 
         fname,  
         os.O_WRONLY+os.O_CREATE+os.O_EXCL,  
         0644, 
   ) 
   if err != nil { 
         msg := fmt.Sprintf( 
               "Unable to create output file: %v", err, 
         ) 
         panic(msg) 
   } 
   ... 
} 
 
func main() { 
   words, err := load("dict.txt") 
   if err != nil { 
         fmt.Println("Unable to load file:", err) 
         os.Exit(1) 
   } 
   anagrams := mapWords(words) 
   write("out.txt", anagrams) 
} 
</pre><p class="calibre10">golang.fyi/ch05/anagram2.go</p><p class="calibre10">In the preceding snippet, the <code class="email">write</code> function calls the <code class="email">panic</code> function if <code class="email">os.OpenFile()</code> method errors out. When the program calls the <code class="email">main</code> function, if there is an output file already in the working directory, the program will panic and crash as shown in the following stack trace, indicating the sequence of calls that caused the crash:</p><pre class="programlisting">
<span class="strong"><strong class="calibre2">&gt; go run anagram2.go
</strong></span>
<span class="strong"><strong class="calibre2">panic: Unable to create output file: open out.txt: file exists</strong></span>
<span class="strong"><strong class="calibre2">goroutine 1 [running]:</strong></span>
<span class="strong"><strong class="calibre2">main.write(0x4e7b30, 0x7, 0xc2080382a0)</strong></span>
<span class="strong"><strong class="calibre2">/Go/src/github.com/vladimirvivien/learning-go/ch05/anagram2.go:72 +0x1a3
</strong></span>
<span class="strong"><strong class="calibre2">main.main()</strong></span>
<span class="strong"><strong class="calibre2">Go/src/github.com/vladimirvivien/learning-go/ch05/anagram2.go:103 +0x1e9</strong></span>
<span class="strong"><strong class="calibre2">exit status 2</strong></span>
</pre></div></div></body></html>