<html><head></head><body>
<div class="book" title="Writing Go tests">
<div class="book" title="Reporting failure"><div class="book"><div class="book"><div class="book"><h2 class="title1" id="calibre_pb_4"><a id="ch12lvl2sec199" class="calibre1"/>Reporting failure</h2></div></div></div><p class="calibre10">By default, the Go test runtime considers a test a success if the test function runs and returns normally without a panic. For example, the following test function is broken, since its expected value is not properly calculated. The test runtime, however, will always report it as passing because it does not include any code to report the failure:</p><pre class="programlisting">func TestVectorDotProd(t *testing.T) { 
    v1 := New(7.887, 4.138).(SimpleVector) 
    v2 := New(-8.802, 6.776).(SimpleVector) 
    actual := v1.DotProd(v2) 
    expect := v1[0]*v2[0] - v1[1]*v2[1] 
    if actual != expect { 
        t.Logf("DotPoduct failed, expecting %d, got %d",  
          expect, actual) 
    } 
} 
</pre><p class="calibre10">golang.fyi/ch12/vec_test.go</p><p class="calibre10">This false positive condition may go unnoticed, especially if the verbose flag is turned off, minimizing any visual clues that it is broken:</p><pre class="programlisting">
<span class="strong"><strong class="calibre2">$&gt; go test -run=VectorDot</strong></span>
<span class="strong"><strong class="calibre2">PASS</strong></span>
<span class="strong"><strong class="calibre2">ok    github.com/vladimirvivien/learning-go/ch12/vector     0.001s</strong></span>
</pre><p class="calibre10">One way the previous test can be fixed is by using the <code class="email">Fail</code> method from type <code class="email">testing.T</code> to signal failure, as shown in the following snippet:</p><pre class="programlisting">func TestVectorDotProd(t *testing.T) { 
... 
    if actual != expect { 
        t.Logf("DotPoduct failed, expecting %d, got %d",  
          expect, actual) 
        t.Fail() 
    } 
} 
</pre><p class="calibre10">So now, when the test is executed, it correctly reports that it is broken, as shown in the following output:</p><pre class="programlisting">
<span class="strong"><strong class="calibre2">$&gt; go test -run=VectorDot</strong></span>
<span class="strong"><strong class="calibre2">--- FAIL: TestVectorDotProd (0.00s)</strong></span>
<span class="strong"><strong class="calibre2">vec_test.go:109: DotPoduct failed, expecting -97.460462, got -41.382286</strong></span>
<span class="strong"><strong class="calibre2">FAIL</strong></span>
<span class="strong"><strong class="calibre2">exit status 1</strong></span>
<span class="strong"><strong class="calibre2">FAIL  github.com/vladimirvivien/learning-go/ch12/vector     0.002s</strong></span>
</pre><p class="calibre10">It is important to understand that method <code class="email">Fail</code> only reports failure and does not halt the execution of a test function. On the other hand, when it makes sense to actually exit the function upon a failed condition, the test API offers the method <code class="email">FailNow</code>, which signals failure and exits the currently executing test function.</p><p class="calibre10">Type <code class="email">testing.T</code> provides the convenience methods <code class="email">Logf</code> and <code class="email">Errorf</code>, which combine both logging and failure reporting. For instance, the following snippet uses the <code class="email">Errorf</code> method, which is equivalent to calling the <code class="email">Logf</code> and <code class="email">Fail</code> methods:</p><pre class="programlisting">func TestVectorMag(t *testing.T) { 
    v := New(-0.221, 7.437) 
    expected := math.Sqrt(v[0]*v[0] + v[1]*v[1]) 
    if v.Mag() != expected { 
   t.Errorf("Magnitude failed, execpted %d, got %d",  
        expected, v.Mag()) 
    } 
} 
</pre><p class="calibre10">golang.fyi/ch12/vector/vec.go</p><p class="calibre10">Type <code class="email">testing.T</code> also offers <code class="email">Fatal</code> and <code class="email">Formatf</code> methods as a way of combining the logging of a message and the immediate termination of a test function.</p></div></div></body></html>